from __future__ import annotations

from pathlib import Path
import sys

TARGET = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('step_rd_candidates.py')
text = TARGET.read_text(encoding='utf-8')
original = text

# 1) Remove stale-result enforcement from the pure/presentation renderer.
start_marker = '''        # Never present/export a Stage-6 decision table produced by an older\n'''
end_marker = '''        call_col = "Go_Investigate_Hold_NoGo" if "Go_Investigate_Hold_NoGo" in df.columns else None\n'''
start = text.find(start_marker)
if start < 0:
    raise SystemExit('Could not find renderer fingerprint-guard start marker; file may have changed.')
end = text.find(end_marker, start)
if end < 0:
    raise SystemExit('Could not find renderer fingerprint-guard end marker; file may have changed.')
# Preserve call_col line; remove only the guard block before it.
text = text[:start] + text[end:]

# 2) Add a pure helper immediately before _recommendation_block.
anchor = '''def _recommendation_block(result_df, report_ready_df=None):\n'''
helper = '''def _report_ready_matches_current_pipeline(report_ready_df) -> bool:\n    """Return True only when a Stage-5 report belongs to the current code.\n\n    This check intentionally lives OUTSIDE ``_recommendation_block``'s rendering\n    logic.  The renderer is also used directly by unit tests and legacy/internal\n    callers with small synthetic dataframes that do not carry session provenance.\n    Production stale-result protection is enforced at the real Stage-6 session\n    call site before the renderer is invoked.\n    """\n    if not isinstance(report_ready_df, pd.DataFrame) or report_ready_df.empty:\n        return True\n    if "Pipeline_Implementation_Fingerprint" not in report_ready_df.columns:\n        return False\n    report_fingerprints = set(\n        report_ready_df["Pipeline_Implementation_Fingerprint"]\n        .dropna().astype(str).str.strip().tolist()\n    )\n    return report_fingerprints == {_pipeline_implementation_fingerprint()}\n\n\n'''
if helper not in text:
    pos = text.find(anchor)
    if pos < 0:
        raise SystemExit('Could not find _recommendation_block definition.')
    text = text[:pos] + helper + text[pos:]

# 3) Enforce the guard ONLY at the actual Stage-6 session-state call site.
old_call = '''    if st.session_state.get("show_final_recommendation"):\n        _recommendation_block(result_df, st.session_state.get("rd_report_ready_df"))\n'''
new_call = '''    if st.session_state.get("show_final_recommendation"):\n        _report_ready_df = st.session_state.get("rd_report_ready_df")\n        if (\n            isinstance(_report_ready_df, pd.DataFrame)\n            and not _report_ready_df.empty\n            and not _report_ready_matches_current_pipeline(_report_ready_df)\n        ):\n            st.warning(\n                "Stage 5 results were generated by an older candidate-discovery "\n                "implementation. Run Candidate Discovery once with the current code "\n                "before using or exporting Stage 6."\n            )\n        else:\n            _recommendation_block(result_df, _report_ready_df)\n'''
if old_call not in text:
    raise SystemExit('Could not find the real Stage-6 recommendation call site; file may have changed.')
text = text.replace(old_call, new_call, 1)

if text == original:
    raise SystemExit('No changes applied.')
backup = TARGET.with_suffix(TARGET.suffix + '.before_stage6_ci_fix')
backup.write_text(original, encoding='utf-8')
TARGET.write_text(text, encoding='utf-8')
print(f'Patched: {TARGET}')
print(f'Backup:  {backup}')
