PLANT_COMPOUND_DATABASE = [
    {
        "Scientific_Name": "Melissa officinalis",
        "Compound": "Rosmarinic acid",
        "Compound_Class": "Phenolic acid",
        "Plant_Part": "Leaf",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Rosmarinic acid",
        "Novelty_Level": "Medium",
    },
    {
        "Scientific_Name": "Melissa officinalis",
        "Compound": "Citral",
        "Compound_Class": "Monoterpene aldehyde",
        "Plant_Part": "Leaf / essential oil",
        "Extraction_Method": "Steam distillation",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Citral",
        "Novelty_Level": "Medium",
    },
    {
        "Scientific_Name": "Melissa officinalis",
        "Compound": "Luteolin",
        "Compound_Class": "Flavonoid",
        "Plant_Part": "Leaf",
        "Extraction_Method": "Hydroalcoholic extract",
        "Extraction_Feasibility": "Medium",
        "Standardization_Marker": "Luteolin",
        "Novelty_Level": "High",
    },
    {
        "Scientific_Name": "Passiflora incarnata",
        "Compound": "Vitexin",
        "Compound_Class": "Flavonoid",
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Vitexin",
        "Novelty_Level": "Medium",
    },
    {
        "Scientific_Name": "Passiflora incarnata",
        "Compound": "Chrysin",
        "Compound_Class": "Flavonoid",
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Hydroalcoholic extract",
        "Extraction_Feasibility": "Medium",
        "Standardization_Marker": "Chrysin",
        "Novelty_Level": "High",
    },
    {
        "Scientific_Name": "Valeriana officinalis",
        "Compound": "Valerenic acid",
        "Compound_Class": "Sesquiterpenic acid",
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Hydroalcoholic extract / dry extract",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Valerenic acid",
        "Novelty_Level": "Low",
    },
    {
        "Scientific_Name": "Lavandula angustifolia",
        "Compound": "Linalool",
        "Compound_Class": "Monoterpene alcohol",
        "Plant_Part": "Flowering tops",
        "Extraction_Method": "Steam distillation / essential oil",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Linalool",
        "Novelty_Level": "Low",
    },
    {
        "Scientific_Name": "Lavandula angustifolia",
        "Compound": "Linalyl acetate",
        "Compound_Class": "Monoterpene ester",
        "Plant_Part": "Flowering tops",
        "Extraction_Method": "Steam distillation / essential oil",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Linalyl acetate",
        "Novelty_Level": "Low",
    },
    {
        "Scientific_Name": "Matricaria chamomilla",
        "Compound": "Apigenin",
        "Compound_Class": "Flavonoid",
        "Plant_Part": "Flower heads",
        "Extraction_Method": "Infusion / hydroalcoholic extract",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Apigenin",
        "Novelty_Level": "Medium",
    },
    {
        "Scientific_Name": "Humulus lupulus",
        "Compound": "Xanthohumol",
        "Compound_Class": "Prenylated chalcone",
        "Plant_Part": "Female inflorescences",
        "Extraction_Method": "Hydroalcoholic extract / CO2 extract",
        "Extraction_Feasibility": "Medium",
        "Standardization_Marker": "Xanthohumol",
        "Novelty_Level": "High",
    },
    {
        "Scientific_Name": "Withania somnifera",
        "Compound": "Withanolides",
        "Compound_Class": "Steroidal lactones",
        "Plant_Part": "Root",
        "Extraction_Method": "Hydroalcoholic extract / standardized extract",
        "Extraction_Feasibility": "High",
        "Standardization_Marker": "Withanolides",
        "Novelty_Level": "High",
    },
    {
        "Scientific_Name": "Ziziphus jujuba",
        "Compound": "Jujubosides",
        "Compound_Class": "Saponins",
        "Plant_Part": "Seed",
        "Extraction_Method": "Aqueous / ethanolic extract",
        "Extraction_Feasibility": "Medium",
        "Standardization_Marker": "Jujubosides",
        "Novelty_Level": "High",
    },
]
