from compound_profile_database import save_compound_profile


COMPOUND_PROFILES = [
    {
        "compound_name": "Rosmarinic acid",
        "compound_class": "Phenolic acid",
        "major_target": "GABAergic system; COX-2; NF-kB; Nrf2",
        "mechanism": "Anti-inflammatory, antioxidant, neuromodulatory potential",
        "evidence_level": "Preclinical + human supportive",
        "activity_score": 88,
        "bioavailability": "Medium",
        "stability": "Medium",
        "extraction_difficulty": "Easy",
        "toxicity": "Low",
        "commercial_interest": "High",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Apigenin",
        "compound_class": "Flavonoid",
        "major_target": "GABA-A receptor; benzodiazepine receptor; COX-2",
        "mechanism": "Anxiolytic-like and anti-inflammatory flavonoid activity",
        "evidence_level": "Preclinical + human supportive",
        "activity_score": 86,
        "bioavailability": "Low",
        "stability": "Medium",
        "extraction_difficulty": "Medium",
        "toxicity": "Low",
        "commercial_interest": "High",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Vitexin",
        "compound_class": "Flavonoid",
        "major_target": "GABAergic system; oxidative stress pathways",
        "mechanism": "Anxiolytic-like and antioxidant activity",
        "evidence_level": "Preclinical",
        "activity_score": 78,
        "bioavailability": "Medium",
        "stability": "Medium",
        "extraction_difficulty": "Easy",
        "toxicity": "Low",
        "commercial_interest": "Medium",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Chrysin",
        "compound_class": "Flavonoid",
        "major_target": "GABA-A receptor; benzodiazepine receptor",
        "mechanism": "Potential benzodiazepine-site modulation",
        "evidence_level": "Preclinical",
        "activity_score": 76,
        "bioavailability": "Low",
        "stability": "Medium",
        "extraction_difficulty": "Medium",
        "toxicity": "Low",
        "commercial_interest": "Medium",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Valerenic acid",
        "compound_class": "Sesquiterpenic acid",
        "major_target": "GABA-A receptor",
        "mechanism": "Modulation of GABA-A receptor activity",
        "evidence_level": "Preclinical + traditional/regulatory support",
        "activity_score": 84,
        "bioavailability": "Medium",
        "stability": "Medium",
        "extraction_difficulty": "Medium",
        "toxicity": "Medium",
        "commercial_interest": "High",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Linalool",
        "compound_class": "Monoterpene alcohol",
        "major_target": "GABAergic system; glutamate system; calcium channels",
        "mechanism": "Sedative, anxiolytic, CNS depressant-like activity",
        "evidence_level": "Preclinical + human supportive",
        "activity_score": 82,
        "bioavailability": "High",
        "stability": "Medium",
        "extraction_difficulty": "Easy",
        "toxicity": "Low",
        "commercial_interest": "High",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Linalyl acetate",
        "compound_class": "Monoterpene ester",
        "major_target": "GABAergic system; autonomic nervous system",
        "mechanism": "Relaxant volatile compound activity",
        "evidence_level": "Preclinical",
        "activity_score": 74,
        "bioavailability": "High",
        "stability": "Medium",
        "extraction_difficulty": "Easy",
        "toxicity": "Low",
        "commercial_interest": "High",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Withanolides",
        "compound_class": "Steroidal lactones",
        "major_target": "HPA axis; GABAergic system; NF-kB",
        "mechanism": "Adaptogenic, anti-stress, anti-inflammatory activity",
        "evidence_level": "Human supportive + preclinical",
        "activity_score": 89,
        "bioavailability": "Medium",
        "stability": "Medium",
        "extraction_difficulty": "Medium",
        "toxicity": "Medium",
        "commercial_interest": "Very high",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Jujubosides",
        "compound_class": "Saponins",
        "major_target": "GABAergic system; serotonergic system",
        "mechanism": "Sedative and sleep-promoting saponins",
        "evidence_level": "Preclinical",
        "activity_score": 80,
        "bioavailability": "Medium",
        "stability": "Medium",
        "extraction_difficulty": "Medium",
        "toxicity": "Low",
        "commercial_interest": "Medium",
        "reference_url": "",
        "source": "Internal curated seed",
    },
    {
        "compound_name": "Baicalin",
        "compound_class": "Flavonoid glycoside",
        "major_target": "GABAergic system; NF-kB; COX-2",
        "mechanism": "Neuroactive, anti-inflammatory and antioxidant activity",
        "evidence_level": "Preclinical + human supportive",
        "activity_score": 87,
        "bioavailability": "Low",
        "stability": "Medium",
        "extraction_difficulty": "Medium",
        "toxicity": "Low",
        "commercial_interest": "High",
        "reference_url": "",
        "source": "Internal curated seed",
    },
]


def seed_compound_profiles():
    saved = 0

    for record in COMPOUND_PROFILES:
        save_compound_profile(record)
        saved += 1

    return saved
