GLOBAL_PLANT_CANDIDATES = [
    {
        "Scientific_Name": "Valeriana officinalis",
        "Common_Name": "Valerian",
        "Region": "Europe / Western Asia",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["valerenic acid", "valepotriates", "bornyl acetate"],
        "Known_Targets": ["GABA-A receptor", "adenosine system"],
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Hydroalcoholic extract / dry extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Melissa officinalis",
        "Common_Name": "Lemon balm",
        "Region": "Europe / Mediterranean",
        "Indications": ["Sleep and relaxation", "Anxiety", "Digestive comfort"],
        "Known_Active_Compounds": ["rosmarinic acid", "citral", "caffeic acid", "luteolin", "apigenin"],
        "Known_Targets": ["GABAergic system", "acetylcholinesterase", "antioxidant pathways"],
        "Plant_Part": "Leaf",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Passiflora incarnata",
        "Common_Name": "Passionflower",
        "Region": "Americas",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["vitexin", "isovitexin", "orientin", "apigenin", "chrysin"],
        "Known_Targets": ["GABAergic system", "benzodiazepine receptor modulation"],
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Lavandula angustifolia",
        "Common_Name": "Lavender",
        "Region": "Mediterranean / Europe",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["linalool", "linalyl acetate", "lavandulol", "terpinen-4-ol"],
        "Known_Targets": ["GABAergic system", "serotonergic system", "calcium channels"],
        "Plant_Part": "Flowering tops / essential oil",
        "Extraction_Method": "Steam distillation / essential oil",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Humulus lupulus",
        "Common_Name": "Hops",
        "Region": "Europe / Western Asia / North America",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["xanthohumol", "8-prenylnaringenin", "humulone", "lupulone"],
        "Known_Targets": ["GABAergic system", "estrogen receptors", "anti-inflammatory pathways"],
        "Plant_Part": "Female inflorescences",
        "Extraction_Method": "Hydroalcoholic extract / CO2 extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Matricaria chamomilla",
        "Common_Name": "German chamomile",
        "Region": "Europe / Western Asia",
        "Indications": ["Sleep and relaxation", "Anxiety", "Digestive comfort", "Skin inflammation"],
        "Known_Active_Compounds": ["apigenin", "bisabolol", "chamazulene", "luteolin"],
        "Known_Targets": ["GABAergic system", "anti-inflammatory pathways", "COX/LOX modulation"],
        "Plant_Part": "Flower heads",
        "Extraction_Method": "Infusion / essential oil / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Tilia cordata",
        "Common_Name": "Linden",
        "Region": "Europe / Western Asia",
        "Indications": ["Sleep and relaxation", "Cough"],
        "Known_Active_Compounds": ["tiliroside", "quercetin", "kaempferol", "mucilage"],
        "Known_Targets": ["mild sedative pathways", "anti-inflammatory pathways"],
        "Plant_Part": "Inflorescences",
        "Extraction_Method": "Infusion / aqueous extract",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Withania somnifera",
        "Common_Name": "Ashwagandha",
        "Region": "India / South Asia / Africa",
        "Indications": ["Sleep and relaxation", "Anxiety", "Stress", "Fatigue"],
        "Known_Active_Compounds": ["withanolides", "withaferin A", "sitoindosides"],
        "Known_Targets": ["HPA axis", "GABAergic system", "anti-inflammatory pathways"],
        "Plant_Part": "Root",
        "Extraction_Method": "Hydroalcoholic extract / standardized extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Gynostemma pentaphyllum",
        "Common_Name": "Jiaogulan",
        "Region": "China / East Asia",
        "Indications": ["Sleep and relaxation", "Stress", "Metabolic health"],
        "Known_Active_Compounds": ["gypenosides", "saponins", "flavonoids"],
        "Known_Targets": ["AMPK", "antioxidant pathways", "anti-inflammatory pathways"],
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Aqueous / ethanolic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Ziziphus jujuba",
        "Common_Name": "Jujube seed",
        "Region": "China / East Asia",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["jujubosides", "spinosin", "flavonoids"],
        "Known_Targets": ["GABAergic system", "serotonergic system"],
        "Plant_Part": "Seed",
        "Extraction_Method": "Aqueous / ethanolic extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Piper methysticum",
        "Common_Name": "Kava",
        "Region": "Pacific Islands",
        "Indications": ["Anxiety", "Sleep and relaxation"],
        "Known_Active_Compounds": ["kavalactones", "kavain", "yangonin"],
        "Known_Targets": ["GABAergic system", "sodium channels", "monoamine oxidase"],
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Aqueous / organic solvent extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Scutellaria baicalensis",
        "Common_Name": "Baikal skullcap",
        "Region": "China / East Asia",
        "Indications": ["Anxiety", "Inflammation", "Sleep and relaxation"],
        "Known_Active_Compounds": ["baicalin", "baicalein", "wogonin"],
        "Known_Targets": ["GABAergic system", "NF-kB", "anti-inflammatory pathways"],
        "Plant_Part": "Root",
        "Extraction_Method": "Ethanolic / aqueous extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },

    {
        "Scientific_Name": "Echinacea purpurea",
        "Common_Name": "Purple coneflower",
        "Region": "North America",
        "Indications": ["Immune support", "Cold & flu / respiratory"],
        "Known_Active_Compounds": ["cichoric acid", "alkamides"],
        "Known_Targets": ["immune modulation", "CB2 receptor"],
        "Plant_Part": "Root / aerial parts",
        "Extraction_Method": "Hydroalcoholic extract / pressed juice",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Sambucus nigra",
        "Common_Name": "Elder",
        "Region": "Europe",
        "Indications": ["Cold & flu / respiratory", "Immune support"],
        "Known_Active_Compounds": ["anthocyanins", "rutin"],
        "Known_Targets": ["antioxidant pathways", "immune modulation"],
        "Plant_Part": "Flower / fruit",
        "Extraction_Method": "Aqueous extract / syrup",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Crataegus monogyna",
        "Common_Name": "Hawthorn",
        "Region": "Europe",
        "Indications": ["Cardiovascular / circulation"],
        "Known_Active_Compounds": ["hyperoside", "procyanidins", "vitexin"],
        "Known_Targets": ["microvascular pathways", "cardiometabolic pathways"],
        "Plant_Part": "Flower / leaf / berry",
        "Extraction_Method": "Hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Allium sativum",
        "Common_Name": "Garlic",
        "Region": "Central Asia / Mediterranean",
        "Indications": ["Cardiovascular / circulation"],
        "Known_Active_Compounds": ["allicin"],
        "Known_Targets": ["cardiometabolic pathways"],
        "Plant_Part": "Bulb",
        "Extraction_Method": "Aqueous / oil macerate / standardized powder",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Silybum marianum",
        "Common_Name": "Milk thistle",
        "Region": "Mediterranean",
        "Indications": ["Liver support / detox"],
        "Known_Active_Compounds": ["silymarin", "silibinin"],
        "Known_Targets": ["hepatoprotective pathways", "Nrf2"],
        "Plant_Part": "Fruit",
        "Extraction_Method": "Hydroalcoholic / standardized extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Cynara scolymus",
        "Common_Name": "Artichoke",
        "Region": "Mediterranean",
        "Indications": ["Liver support / detox", "Digestive comfort"],
        "Known_Active_Compounds": ["cynarin", "chlorogenic acid"],
        "Known_Targets": ["bile flow", "digestive support"],
        "Plant_Part": "Leaf",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Boswellia serrata",
        "Common_Name": "Frankincense",
        "Region": "South Asia / Middle East",
        "Indications": ["Joint & muscle comfort"],
        "Known_Active_Compounds": ["boswellic acids"],
        "Known_Targets": ["anti-inflammatory pathways", "COX-2"],
        "Plant_Part": "Resin",
        "Extraction_Method": "Resin extract / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Curcuma longa",
        "Common_Name": "Turmeric",
        "Region": "South Asia",
        "Indications": ["Joint & muscle comfort", "Inflammation"],
        "Known_Active_Compounds": ["curcumin", "turmerones"],
        "Known_Targets": ["NF-kB", "COX-2", "Nrf2"],
        "Plant_Part": "Rhizome",
        "Extraction_Method": "Standardized extract / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Panax ginseng",
        "Common_Name": "Asian ginseng",
        "Region": "East Asia",
        "Indications": ["Energy / fatigue"],
        "Known_Active_Compounds": ["ginsenosides"],
        "Known_Targets": ["HPA axis", "AMPK", "immune modulation"],
        "Plant_Part": "Root",
        "Extraction_Method": "Hydroalcoholic / standardized extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Rhodiola rosea",
        "Common_Name": "Rhodiola",
        "Region": "Northern Europe / Asia",
        "Indications": ["Energy / fatigue", "Stress"],
        "Known_Active_Compounds": ["rosavins", "salidroside"],
        "Known_Targets": ["HPA axis", "anti-fatigue pathways"],
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Standardized hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Berberis vulgaris",
        "Common_Name": "Barberry",
        "Region": "Europe / Middle East",
        "Indications": ["Metabolic & blood sugar support"],
        "Known_Active_Compounds": ["berberine"],
        "Known_Targets": ["AMPK", "PPAR-gamma", "gut microbiota"],
        "Plant_Part": "Root / bark",
        "Extraction_Method": "Hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Cinnamomum verum",
        "Common_Name": "Cinnamon",
        "Region": "South Asia",
        "Indications": ["Metabolic & blood sugar support"],
        "Known_Active_Compounds": ["cinnamaldehyde"],
        "Known_Targets": ["insulin signaling", "anti-inflammatory pathways"],
        "Plant_Part": "Bark",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Camellia sinensis",
        "Common_Name": "Green tea",
        "Region": "East Asia",
        "Indications": ["Weight management", "Metabolic & blood sugar support"],
        "Known_Active_Compounds": ["EGCG", "caffeine"],
        "Known_Targets": ["AMPK", "adenosine receptor", "antioxidant pathways"],
        "Plant_Part": "Leaf",
        "Extraction_Method": "Aqueous / standardized extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Cimicifuga racemosa",
        "Common_Name": "Black cohosh",
        "Region": "North America",
        "Indications": ["Menopause support"],
        "Known_Active_Compounds": ["triterpene glycosides"],
        "Known_Targets": ["hormonal pathways", "serotonergic system"],
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Hydroalcoholic / standardized extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Trigonella foenum-graecum",
        "Common_Name": "Fenugreek",
        "Region": "Middle East / South Asia",
        "Indications": ["Menopause support", "Metabolic & blood sugar support"],
        "Known_Active_Compounds": ["diosgenin", "4-hydroxyisoleucine"],
        "Known_Targets": ["metabolic pathways", "insulin secretion"],
        "Plant_Part": "Seed",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Vitex agnus-castus",
        "Common_Name": "Chaste tree",
        "Region": "Mediterranean",
        "Indications": ["Menstrual / PMS support"],
        "Known_Active_Compounds": ["agnuside"],
        "Known_Targets": ["hormonal pathways", "dopaminergic system"],
        "Plant_Part": "Fruit",
        "Extraction_Method": "Hydroalcoholic / standardized extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Serenoa repens",
        "Common_Name": "Saw palmetto",
        "Region": "North America",
        "Indications": ["Prostate / men's health"],
        "Known_Active_Compounds": ["fatty acid sterols"],
        "Known_Targets": ["hormonal pathways", "anti-inflammatory pathways"],
        "Plant_Part": "Fruit",
        "Extraction_Method": "Lipophilic (CO2 or hexane) extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Urtica dioica",
        "Common_Name": "Nettle",
        "Region": "Europe / Asia",
        "Indications": ["Prostate / men's health", "Joint & muscle comfort"],
        "Known_Active_Compounds": ["chlorogenic acid", "lignans"],
        "Known_Targets": ["hormonal pathways", "antioxidant pathways"],
        "Plant_Part": "Root / leaf",
        "Extraction_Method": "Hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Vaccinium macrocarpon",
        "Common_Name": "Cranberry",
        "Region": "North America",
        "Indications": ["Urinary tract health"],
        "Known_Active_Compounds": ["proanthocyanidins"],
        "Known_Targets": ["antimicrobial pathways", "microvascular pathways"],
        "Plant_Part": "Fruit",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Hypericum perforatum",
        "Common_Name": "St John's wort",
        "Region": "Europe",
        "Indications": ["Headache / mood support"],
        "Known_Active_Compounds": ["hypericin", "hyperforin"],
        "Known_Targets": ["monoamine system", "monoamine reuptake modulation"],
        "Plant_Part": "Flowering tops",
        "Extraction_Method": "Hydroalcoholic / standardized extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Crocus sativus",
        "Common_Name": "Saffron",
        "Region": "Iran / Mediterranean",
        "Indications": ["Headache / mood support"],
        "Known_Active_Compounds": ["crocin", "safranal"],
        "Known_Targets": ["serotonergic system", "antioxidant pathways"],
        "Plant_Part": "Stigma",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Centella asiatica",
        "Common_Name": "Gotu kola",
        "Region": "South Asia",
        "Indications": ["Hair, skin & nail beauty-from-within", "Wound healing"],
        "Known_Active_Compounds": ["asiaticoside", "madecassoside"],
        "Known_Targets": ["collagen synthesis", "anti-inflammatory pathways"],
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Vaccinium myrtillus",
        "Common_Name": "Bilberry",
        "Region": "Europe",
        "Indications": ["Eye health"],
        "Known_Active_Compounds": ["anthocyanins"],
        "Known_Targets": ["antioxidant pathways", "microvascular pathways"],
        "Plant_Part": "Fruit",
        "Extraction_Method": "Aqueous / standardized extract",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
]
