GLOBAL_PLANT_CANDIDATES = [
    {
        "Scientific_Name": "Valeriana officinalis",
        "Common_Name": "Valerian",
        "Region": "Europe / Western Asia",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["valerenic acid", "valepotriates", "bornyl acetate"],
        "Known_Targets": ["GABA-A receptor", "adenosine system"],
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Hydroalcoholic extract / dry extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Melissa officinalis",
        "Common_Name": "Lemon balm",
        "Region": "Europe / Mediterranean",
        "Indications": ["Sleep and relaxation", "Anxiety", "Digestive comfort"],
        "Known_Active_Compounds": ["rosmarinic acid", "citral", "caffeic acid", "luteolin", "apigenin"],
        "Known_Targets": ["GABAergic system", "acetylcholinesterase", "antioxidant pathways"],
        "Plant_Part": "Leaf",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Passiflora incarnata",
        "Common_Name": "Passionflower",
        "Region": "Americas",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["vitexin", "isovitexin", "orientin", "apigenin", "chrysin"],
        "Known_Targets": ["GABAergic system", "benzodiazepine receptor modulation"],
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Aqueous / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Lavandula angustifolia",
        "Common_Name": "Lavender",
        "Region": "Mediterranean / Europe",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["linalool", "linalyl acetate", "lavandulol", "terpinen-4-ol"],
        "Known_Targets": ["GABAergic system", "serotonergic system", "calcium channels"],
        "Plant_Part": "Flowering tops / essential oil",
        "Extraction_Method": "Steam distillation / essential oil",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Humulus lupulus",
        "Common_Name": "Hops",
        "Region": "Europe / Western Asia / North America",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["xanthohumol", "8-prenylnaringenin", "humulone", "lupulone"],
        "Known_Targets": ["GABAergic system", "estrogen receptors", "anti-inflammatory pathways"],
        "Plant_Part": "Female inflorescences",
        "Extraction_Method": "Hydroalcoholic extract / CO2 extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Matricaria chamomilla",
        "Common_Name": "German chamomile",
        "Region": "Europe / Western Asia",
        "Indications": ["Sleep and relaxation", "Anxiety", "Digestive comfort", "Skin inflammation"],
        "Known_Active_Compounds": ["apigenin", "bisabolol", "chamazulene", "luteolin"],
        "Known_Targets": ["GABAergic system", "anti-inflammatory pathways", "COX/LOX modulation"],
        "Plant_Part": "Flower heads",
        "Extraction_Method": "Infusion / essential oil / hydroalcoholic extract",
        "EMA_Status": "Yes",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Tilia cordata",
        "Common_Name": "Linden",
        "Region": "Europe / Western Asia",
        "Indications": ["Sleep and relaxation", "Cough"],
        "Known_Active_Compounds": ["tiliroside", "quercetin", "kaempferol", "mucilage"],
        "Known_Targets": ["mild sedative pathways", "anti-inflammatory pathways"],
        "Plant_Part": "Inflorescences",
        "Extraction_Method": "Infusion / aqueous extract",
        "EMA_Status": "Yes",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Withania somnifera",
        "Common_Name": "Ashwagandha",
        "Region": "India / South Asia / Africa",
        "Indications": ["Sleep and relaxation", "Anxiety", "Stress", "Fatigue"],
        "Known_Active_Compounds": ["withanolides", "withaferin A", "sitoindosides"],
        "Known_Targets": ["HPA axis", "GABAergic system", "anti-inflammatory pathways"],
        "Plant_Part": "Root",
        "Extraction_Method": "Hydroalcoholic extract / standardized extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Gynostemma pentaphyllum",
        "Common_Name": "Jiaogulan",
        "Region": "China / East Asia",
        "Indications": ["Sleep and relaxation", "Stress", "Metabolic health"],
        "Known_Active_Compounds": ["gypenosides", "saponins", "flavonoids"],
        "Known_Targets": ["AMPK", "antioxidant pathways", "anti-inflammatory pathways"],
        "Plant_Part": "Aerial parts",
        "Extraction_Method": "Aqueous / ethanolic extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Ziziphus jujuba",
        "Common_Name": "Jujube seed",
        "Region": "China / East Asia",
        "Indications": ["Sleep and relaxation", "Anxiety"],
        "Known_Active_Compounds": ["jujubosides", "spinosin", "flavonoids"],
        "Known_Targets": ["GABAergic system", "serotonergic system"],
        "Plant_Part": "Seed",
        "Extraction_Method": "Aqueous / ethanolic extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
    {
        "Scientific_Name": "Piper methysticum",
        "Common_Name": "Kava",
        "Region": "Pacific Islands",
        "Indications": ["Anxiety", "Sleep and relaxation"],
        "Known_Active_Compounds": ["kavalactones", "kavain", "yangonin"],
        "Known_Targets": ["GABAergic system", "sodium channels", "monoamine oxidase"],
        "Plant_Part": "Root / rhizome",
        "Extraction_Method": "Aqueous / organic solvent extract",
        "EMA_Status": "No",
        "Research_Priority": "Medium",
    },
    {
        "Scientific_Name": "Scutellaria baicalensis",
        "Common_Name": "Baikal skullcap",
        "Region": "China / East Asia",
        "Indications": ["Anxiety", "Inflammation", "Sleep and relaxation"],
        "Known_Active_Compounds": ["baicalin", "baicalein", "wogonin"],
        "Known_Targets": ["GABAergic system", "NF-kB", "anti-inflammatory pathways"],
        "Plant_Part": "Root",
        "Extraction_Method": "Ethanolic / aqueous extract",
        "EMA_Status": "No",
        "Research_Priority": "High",
    },
]
