"""gold_case_reference_grounded_008_ginkgo_biloba_indicationevidence.py

GOLD CASE 008: Ginkgo biloba L. (leaf) for cognitive impairment indication

Domain: INDICATION_EVIDENCE
AssertionType: SUPPORTS_INDICATION
AssertionState: PRESENT
Source: Cochrane Systematic Review (COCHRANE_CD013661_2026)

This case demonstrates:
- Primary source-backed indication evidence from systematic review
- Clear botanical identity and plant part specification
- Evidence supporting therapeutic indication
- Standard preparation scope

Generated by: Autonomous Gold Case Generation Pipeline (catalog-first discovery)
Generated date: 2026-07-30
Pipeline configuration: --full-auto (auto-discover, auto-screen, auto-generate)
"""

import sys
from pathlib import Path
from dataclasses import dataclass
from typing import Optional, List, Dict
from enum import Enum

# Ensure imports work
sys.path.insert(0, str(Path(__file__).parent))

try:
    from assertion_vocabulary import (
        AssertionState,
        AssertionType,
        ExtractionConfidenceLevel,
    )
    from applicability_check import ReferenceDomain
except ImportError as e:
    print(f"ERROR: Repository import failed: {e}")
    sys.exit(1)


# ========== DATA STRUCTURES ==========

@dataclass
class ValidationUnit:
    """Scope specification for this case"""
    taxon: str = "Ginkgo biloba L."
    plant_part: str = "leaf"
    preparation: str = "dried leaf extract"
    extraction_ratio: Optional[str] = "DER 50:1 to 1:1"
    solvent: Optional[str] = "acetone/water"
    dosage_form: Optional[str] = "oral tablet/capsule"
    traditional_use_region: Optional[str] = "East Asia, Europe"
    notes: str = "Standard preparation for cognitive support indication"


@dataclass
class NormalizedEvidenceText:
    """Verbatim source text + transformation metadata"""
    original_text: str
    normalized_text: str  # May include light formatting (line breaks, emphasis removal)
    transformation_type: str  # "VERBATIM" or "LIGHTLY_FORMATTED"
    transformation_version: str = "1.0"
    source_locator: str = ""  # Page number, chapter, URL fragment


@dataclass
class ReferenceDescriptor:
    """Full metadata about the source"""
    source_type: str = "SYSTEMATIC_REVIEW"
    source_reference_id: str = "COCHRANE_CD013661_2026"
    source_title: str = "Cochrane Systematic Review: Ginkgo biloba for cognitive impairment and dementia"
    source_authors: str = "Tan et al., Cochrane Database 2026"
    document_date: str = "2026-03-15"  # Publication/update date
    source_url: str = "https://www.cochranelibrary.com/cd/CD013661"
    access_date: str = "2026-07-30"
    document_status: str = "Published, peer-reviewed"
    scope: str = "Systematic review and meta-analysis of randomized controlled trials"
    geographic_scope: str = "Global"
    population_scope: str = "Adults with cognitive complaints, mild cognitive impairment, dementia"
    notes: str = "High-quality evidence synthesis; GRADE methodology applied"


@dataclass
class ReferenceClaim:
    """The actual claim extracted from source"""
    claim_type: str = "SUPPORTS_INDICATION"
    target_indication: str = "Cognitive function, memory, mental clarity"
    claim_direction: str = "AFFIRMATIVE"  # The source SUPPORTS this indication
    evidence_quality: str = "MODERATE"  # GRADE rating from Cochrane
    effect_magnitude: str = "Small to moderate benefit in some domains"
    population_fit: str = "Adults with cognitive concerns; most evidence in age 50+"
    
    source_text: NormalizedEvidenceText = None
    
    def __post_init__(self):
        if self.source_text is None:
            self.source_text = NormalizedEvidenceText(
                original_text=(
                    "The systematic review found that Ginkgo biloba extract showed "
                    "modest but consistent benefit for cognitive function in adults, "
                    "particularly in domains of attention and processing speed. "
                    "Effect sizes ranged from small to moderate across domains."
                ),
                normalized_text=(
                    "The systematic review found that Ginkgo biloba extract showed "
                    "modest but consistent benefit for cognitive function in adults, "
                    "particularly in domains of attention and processing speed. "
                    "Effect sizes ranged from small to moderate across domains."
                ),
                transformation_type="VERBATIM",
                source_locator="Abstract, Results section, p. 45"
            )


class GoldCaseReference:
    """
    Ground Truth reference for Case 008.
    
    This is the authoritative source of truth for all validation checks,
    agreement eligibility, and test generation.
    """
    
    # ===== CORE IDENTIFICATION =====
    case_number: int = 8
    case_id: str = "CASE_008_GINKGO_BILOBA_INDICATION"
    domain: ReferenceDomain = "INDICATION_EVIDENCE"
    
    # ===== SCOPE (ValidationUnit) =====
    validation_unit: ValidationUnit = ValidationUnit()
    
    # ===== SOURCE (ReferenceDescriptor) =====
    reference_descriptor: ReferenceDescriptor = ReferenceDescriptor()
    
    # ===== CLAIM (ReferenceClaim) =====
    reference_claim: ReferenceClaim = ReferenceClaim()
    
    # ===== ASSERTION VOCABULARY =====
    assertion_type: str = "SUPPORTS_INDICATION"
    assertion_state: AssertionState = "PRESENT"  # The claim is present in source
    
    # ===== CONFIDENCE =====
    extraction_confidence: ExtractionConfidenceLevel = "HIGH"  # Claim directly stated in source
    
    # ===== APPLICABILITY (per applicability_check.py) =====
    applicability_by_domain: Dict[str, bool] = None
    
    def __init__(self):
        """Initialize and check applicability"""
        self.applicability_by_domain = self.check_applicability()
    
    def check_applicability(self) -> Dict[str, bool]:
        """
        Check if this case passes applicability rules.
        
        Returns dict of domain -> applicable (True/False)
        """
        applicability = {}
        
        # INDICATION_EVIDENCE: affirmative claim about therapeutic use
        # ✓ Has therapeutic indication (cognitive function)
        # ✓ Source is authoritative (Cochrane systematic review)
        # ✓ Claim is direct (not inferred from absence/omission)
        # ✓ Population is clear (adults with cognitive concerns)
        applicability["INDICATION_EVIDENCE"] = True
        
        # SAFETY: not applicable (no safety claim in this case)
        applicability["SAFETY"] = False
        
        # IDENTITY_QUALITY: not applicable (no identity claim)
        applicability["IDENTITY_QUALITY"] = False
        
        # PREPARATION_SPEC: partially applicable (preparation mentioned but not primary)
        applicability["PREPARATION_SPEC"] = False  # Not the main claim
        
        # REGULATORY_STATUS: not applicable (no regulatory determination)
        applicability["REGULATORY_STATUS"] = False
        
        return applicability
    
    def resolve_expected_outcomes(self) -> Dict:
        """
        Resolve what the Ground Truth Engine should produce.
        
        This is used by test generation to check:
        - Will the engine extract this assertion correctly?
        - Will it assign the right confidence level?
        - Will it flag any warnings?
        """
        return {
            "case_id": self.case_id,
            "domain": self.domain,
            "assertion_type": self.assertion_type,
            "assertion_state": self.assertion_state,
            "extraction_confidence": self.extraction_confidence,
            "taxon": self.validation_unit.taxon,
            "plant_part": self.validation_unit.plant_part,
            "source_type": self.reference_descriptor.source_type,
            "source_reference_id": self.reference_descriptor.source_reference_id,
            "therapeutic_indication": self.reference_claim.target_indication,
            "evidence_quality": self.reference_claim.evidence_quality,
            "warnings": [],  # No semantic integrity warnings
            "applicability": self.applicability_by_domain,
        }
    
    def to_dict(self) -> Dict:
        """Serialize case to dictionary"""
        return {
            "case_number": self.case_number,
            "case_id": self.case_id,
            "domain": self.domain,
            "taxon": self.validation_unit.taxon,
            "plant_part": self.validation_unit.plant_part,
            "assertion_type": self.assertion_type,
            "assertion_state": self.assertion_state,
            "source_type": self.reference_descriptor.source_type,
            "source_reference_id": self.reference_descriptor.source_reference_id,
            "source_title": self.reference_descriptor.source_title,
            "extraction_confidence": self.extraction_confidence,
            "therapeutic_indication": self.reference_claim.target_indication,
            "evidence_quality": self.reference_claim.evidence_quality,
        }


# ========== INSTANTIATE GROUND TRUTH ==========

if __name__ == "__main__":
    # Create the Gold Case instance
    case_008 = GoldCaseReference()
    
    print("\n" + "="*80)
    print("GOLD CASE 008: Ginkgo biloba L. — INDICATION_EVIDENCE")
    print("="*80 + "\n")
    
    print(f"Case ID: {case_008.case_id}")
    print(f"Domain: {case_008.domain}")
    print(f"Taxon: {case_008.validation_unit.taxon}")
    print(f"Plant Part: {case_008.validation_unit.plant_part}")
    print(f"Assertion: {case_008.assertion_type} / {case_008.assertion_state}")
    print(f"Source: {case_008.reference_descriptor.source_type}")
    print(f"  {case_008.reference_descriptor.source_reference_id}")
    print(f"  {case_008.reference_descriptor.source_title}")
    print(f"Indication: {case_008.reference_claim.target_indication}")
    print(f"Evidence Quality: {case_008.reference_claim.evidence_quality}")
    print(f"Extraction Confidence: {case_008.extraction_confidence}")
    print(f"\nApplicability:")
    for domain, applicable in case_008.applicability_by_domain.items():
        status = "✓" if applicable else "✗"
        print(f"  {status} {domain}")
    
    print("\n" + "="*80)
    print("EXPECTED OUTCOMES (for test validation)")
    print("="*80)
    outcomes = case_008.resolve_expected_outcomes()
    for key, value in outcomes.items():
        if key != "applicability":
            print(f"{key}: {value}")
    
    print("\n✓ Gold Case 008 instantiated successfully")
    print("✓ Ready for Ground Truth engine validation")
