"""Static/runtime-light regression locks for Stage-5 code-version invalidation.

This test intentionally avoids importing step_rd_candidates because the minimal
CI environment used for core scientific tests may not install Streamlit.
"""
from pathlib import Path


def test_step5_run_key_and_engine_cache_include_pipeline_fingerprint():
    source = Path(__file__).with_name("step_rd_candidates.py").read_text(encoding="utf-8")
    assert "def _pipeline_implementation_fingerprint()" in source
    assert 'f"{ENGINE_CACHE_VERSION}:{_pipeline_implementation_fingerprint()}"' in source
    # The per-session exact-input reuse key must also contain the code hash.
    run_key_block = source[source.index("def _candidate_discovery_run_key("):source.index("def _offline_engine()")]
    assert "_pipeline_implementation_fingerprint()" in run_key_block


def test_stage6_rejects_stale_unfingerprinted_report_and_exports_fingerprint():
    source = Path(__file__).with_name("step_rd_candidates.py").read_text(encoding="utf-8")
    assert "Stage 5 results were generated by an older candidate-discovery" in source
    assert source.count("Pipeline_Implementation_Fingerprint") >= 5
